CREATE TABLE usuarios (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(150) NOT NULL,
    cpf           VARCHAR(11)  NOT NULL,
    email         VARCHAR(255) NOT NULL,
    senha_hash    VARCHAR(72)  NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USUARIO_COMUM',
    ativo         BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_usuarios_role CHECK (role IN ('ADMIN', 'USUARIO_COMUM')),

    -- CPF guardado sem mascara, so digitos. Uma unica representacao por CPF.
    CONSTRAINT ck_usuarios_cpf CHECK (cpf ~ '^[0-9]{11}$')
);

-- CPF e a credencial de login: unicidade e requisito de seguranca, nao so de
-- integridade. Dois usuarios com o mesmo CPF tornariam o login ambiguo.
CREATE UNIQUE INDEX uk_usuarios_cpf ON usuarios (cpf);

-- E-mail unico ignorando caixa, para "Leo@x.com" e "leo@x.com" nao virarem
-- duas contas. Indice funcional nao exige extensao do Postgres.
CREATE UNIQUE INDEX uk_usuarios_email ON usuarios (lower(email));

COMMENT ON COLUMN usuarios.senha_hash IS 'Hash BCrypt (60 chars). Nunca senha em texto puro.';
COMMENT ON COLUMN usuarios.cpf        IS 'Somente digitos, sem mascara. Credencial de login.';
