CREATE TABLE enderecos (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id    BIGINT       NOT NULL,
    cep           VARCHAR(8)   NOT NULL,
    logradouro    VARCHAR(255) NOT NULL,
    numero        VARCHAR(20)  NOT NULL,
    complemento   VARCHAR(100),
    bairro        VARCHAR(100) NOT NULL,
    cidade        VARCHAR(100) NOT NULL,
    uf            VARCHAR(2)   NOT NULL,
    principal     BOOLEAN      NOT NULL DEFAULT FALSE,
    criado_em     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_enderecos_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE,

    -- CEP guardado sem mascara, so digitos, para nao existirem duas
    -- representacoes do mesmo CEP ("01001-000" vs "01001000").
    CONSTRAINT ck_enderecos_cep CHECK (cep ~ '^[0-9]{8}$'),
    CONSTRAINT ck_enderecos_uf  CHECK (uf  ~ '^[A-Z]{2}$')
);

-- O Postgres NAO cria indice automatico em coluna de FK. Sem este indice a
-- consulta "enderecos do usuario X" e o proprio ON DELETE CASCADE varrem a
-- tabela inteira.
CREATE INDEX idx_enderecos_usuario_id ON enderecos (usuario_id);

-- A regra de negocio gravada no schema: indice unico PARCIAL.
-- So indexa as linhas com principal = TRUE; dentro desse subconjunto
-- usuario_id precisa ser unico. Logo: N enderecos por usuario, no maximo 1
-- principal. Um UNIQUE (usuario_id, principal) comum estaria ERRADO, pois
-- limitaria tambem a 1 o numero de enderecos nao-principais.
CREATE UNIQUE INDEX uk_enderecos_um_principal_por_usuario
    ON enderecos (usuario_id)
    WHERE principal = TRUE;
